import {
    Palette,
    Megaphone,
    Newspaper,
    BriefcaseBusiness,
    Globe2,
    Lightbulb,
    CalendarDays,
  } from "lucide-react";
  
  export const services = [
    {
      number: "01",
      title: "Branding & Creative",
      tagline: "Build a Brand People Remember",
      description:
        "We help businesses establish professional, consistent and compelling identities.",
      href: "/services/branding",
      icon: Palette,
      items: [
        "Logo design",
        "Corporate identity",
        "Brand strategy",
        "Brand positioning",
        "Business profiles",
        "Company profiles",
        "Personal branding",
        "Brand guidelines",
        "Marketing materials",
        "Posters and brochures",
        "Presentation design",
        "Website content",
        "Campaign creative",
        "Visual communication",
      ],
      cta: "Build My Brand",
    },
  
    {
      number: "02",
      title: "Digital Marketing",
      tagline: "Turn Digital Visibility Into Business Growth",
      description:
        "Our digital marketing solutions help brands reach, engage and convert their target audiences.",
      href: "/services/digital-marketing",
      icon: Megaphone,
      items: [
        "Social media management",
        "Social media strategy",
        "Content creation",
        "Digital advertising",
        "Campaign management",
        "Lead generation",
        "Email marketing",
        "Online reputation",
        "Digital strategy",
        "Search visibility",
        "Influencer campaigns",
        "Analytics and reporting",
      ],
    },
  
    {
      number: "03",
      title: "Media & Public Relations",
      tagline: "Tell Your Story. Build Your Reputation.",
      description:
        "VEI helps individuals and organizations develop strategic public profiles.",
      href: "/services/media-pr",
      icon: Newspaper,
      items: [
        "Press releases",
        "Media campaigns",
        "Business features",
        "Executive interviews",
        "Video interviews",
        "Podcast appearances",
        "Public relations",
        "Corporate communications",
        "Event coverage",
        "Brand storytelling",
        "Reputation management",
        "Media relations",
      ],
    },
  
    {
      number: "04",
      title: "Business Development",
      tagline: "From Visibility to Business Opportunities",
      description:
        "Visibility is valuable when it produces opportunities. Our business development services help clients identify and pursue growth opportunities.",
      href: "/services/business-development",
      icon: BriefcaseBusiness,
      items: [
        "Business strategy",
        "Market research",
        "Business opportunity identification",
        "Lead generation",
        "Partnership development",
        "Customer acquisition strategy",
        "Market-entry strategy",
        "Business matchmaking",
        "Strategic introductions",
        "Growth consulting",
        "Sales strategy",
      ],
    },
  
    {
      number: "05",
      title: "International Market Access",
      tagline: "Think Beyond Borders",
      description:
        "VEI supports businesses and organizations looking to connect with new markets.",
      href: "/services/international-market-access",
      icon: Globe2,
      items: [
        "International business networking",
        "Market research",
        "Market-entry support",
        "Partner identification",
        "Business introductions",
        "Trade connections",
        "International events",
        "Cross-border collaborations",
        "Investment networking",
        "Expansion strategy",
      ],
      cta: "Explore Global Opportunities",
    },
  
    {
      number: "06",
      title: "Business Consulting",
      tagline: "Clarity Before Growth",
      description:
        "Our consulting services help entrepreneurs and organizations make better strategic decisions.",
      href: "/services/consulting",
      icon: Lightbulb,
      items: [
        "Business startup strategy",
        "Business model development",
        "Business planning",
        "Branding strategy",
        "Marketing strategy",
        "Growth strategy",
        "Market positioning",
        "Digital transformation",
        "Partnership strategy",
        "International expansion",
      ],
    },
  
    {
      number: "07",
      title: "Events & Activations",
      tagline:
        "Create Visibility, Networking and Commercial Opportunities",
      description:
        "We design and manage events that create visibility, networking and commercial opportunities.",
      href: "/services/events-activations",
      icon: CalendarDays,
      items: [
        "Conferences",
        "Business forums",
        "Exhibitions",
        "Networking events",
        "Corporate events",
        "Product launches",
        "Awards",
        "Workshops",
        "Summits",
        "Brand activations",
      ],
    },
  ];